App_Base/urls.py
from django.urls import path
from .views import Home, Login, Logout
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(Home.as_view()),  name='home'),
    path('login/', Login.as_view(),  name='login'),
    path('logout/', login_required(Logout.as_view()),  name='logout')
]

LegalAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Base.urls')),
    path('usuario/', include('App_Usuario.urls')),
    path('calendario/', include('App_Calendario.urls')),
    path('cliente/', include('App_SolicitudCliente.urls')),
    path('casojuridico/', include('App_RegistroCausa.urls'))
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Base/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.

class TipoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class EstadoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class ExtraUser(models.Model):
    user = models.OneToOneField(User, null=False, blank=True, on_delete=models.CASCADE, primary_key=True)
    rut = models.CharField(max_length=10, unique=True)
    tipo = models.ForeignKey(TipoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.user.first_name + ' ' + self.user.last_name)


class GastoOficina(models.Model):
    nombre_gasto = models.CharField(max_length=25)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre_gasto)


class Gastos_User(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    gasto = models.ForeignKey(GastoOficina, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    valor = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.gasto)


class Reunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)
    fecha_inicio = models.CharField(max_length=40, default=False)
    fecha_final = models.CharField(max_length=40, default=False)
    todo_Dia = models.BooleanField(default=False)
    color = models.CharField(max_length=6, default='ffffff')
    tema_reunion = models.CharField(max_length=30)
    observacion = models.TextField(null=False, blank=True)
    caso_juridico = models.IntegerField(default=0)
    url = models.CharField(max_length=200, default=False)

    def __str__(self):
        return '{}'.format(self.tema_reunion + ' ' + str(self.fecha_inicio)+ ' ' + str(self.fecha_final))


class UserReunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    reunion = models.ForeignKey(Reunion, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.reunion)


class Cliente(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.rut + ' ' + self.nombre)


class Materia(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre)


class TemaJuridico(models.Model):
    materia = models.ForeignKey(Materia, blank=True, on_delete=models.CASCADE)
    nombre_tema = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.nombre_tema + ' ' + self.materia.nombre)


class Solicitud(models.Model):
    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=50)
    observaciones = models.TextField()
    demandado_nombre = models.CharField(max_length=100, null=True)
    demandado_rut = models.CharField(max_length=100, null=True)
    demandado_telefono = models.CharField(max_length=100, null=True)
    demandado_direccion = models.CharField(max_length=100, null=True)

    def __str__(self):
        return '{}'.format(self.cliente.nombre + ' ' + self.tema_juridico.nombre_tema)


def generate_path(instance, filename):
    return os.path.join("documents", str(instance.rut), filename)


class DocumentoSolicitud(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.rut)


class Documentacion(models.Model):

    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.rut)


class CasoJuridico(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    nombre_caso = models.CharField(max_length=40)
    fecha_inicio = models.DateField()
    fecha_termino = models.DateField()
    n_rol_tibunal= models.CharField(max_length=80)
    estado = models.CharField(max_length=50)
    instancia = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.nombre_caso)


class UserCaso(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.user.user.username + ' ' + self.caso_juridico.nombre_caso)


class Tribunal(models.Model):
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.nombre)


class Etapa(models.Model):
    caso = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre_etapa = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    descripcion = models.TextField()
    fecha_termini = models.TimeField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_etapa + ' ' + self.caso.nombre_caso)


class Actividad(models.Model):
    etapa = models.ForeignKey(Etapa, blank=True, on_delete=models.CASCADE)
    nombre_actividad = models.CharField(max_length=50)
    fecha_hora = models.DateTimeField()
    descripcion = models.TextField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_actividad)


class Notificacion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    enlace = models.CharField(max_length=100)
    fecha_hora = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.titulo)

templates/casojuridico/listadodecasos.html
{% extends 'base/base.html' %}{% load staticfiles %}
{% block title %} Nuevo usuario {% endblock %}
{% block ccs %}

  <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
{% endblock ccs %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <div class="col-lg-6">
            <i class="fa fa-user-plus fa-fw"></i>
            <h3 class="box-title"> Listado de casos juridicos</h3>
        </div>
        <div class="col-lg-6" align="right">
            <a href="" data-toggle="modal" data-target="#modal-default">
                <h3 class="box-title"> Agregar caso juridico</h3>
                <i class="fa fa-user-plus fa-fw"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <div class="list">
            <div class="row header-list" align="center">
                <div class="col-lg-2">
                    Nombre de causa
                </div>
                <div class="col-lg-1">
                    N° de Rol
                </div>
                <div class="col-lg-2">
                    Cliente
                </div>
                <div class="col-lg-2">
                    Fecha inicio y termino
                </div>
                <div class="col-lg-2">
                    Instancia
                </div>
                <div class="col-lg-2">
                    Demandado
                </div>
            </div>
            {% for foo in casos %}
            <div class="row body-list modal-down" align="center">
                <div class="col-lg-2">
                    {{ foo.nombre_caso }}
                </div>
                <div class="col-lg-1">
                    {{ foo.n_rol_tibunal }}
                </div>
                <div class="col-lg-2">
                    <b>{{ foo.solicitud.cliente.rut }}</b> <br> {{ foo.solicitud.cliente.nombre }}
                </div>
                <div class="col-lg-2">
                    {{ foo.fecha_inicio }} <br> {{ foo.fecha_termino }}
                </div>
                <div class="col-lg-2">
                    {{ foo.instancia }}
                </div>
                <div class="col-lg-2">
                    <b>{{ foo.solicitud.demandado_rut }}</b> <br> {{ foo.solicitud.demandado_nombre }}
                </div>
                <div class="col-lg-1">
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget=""><i class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="modal fade" id="modal-default" style="display: none;">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Seleccione solicitud</h4>
              </div>
              <div class="modal-body">
                  <select name="select_solicitudes" id="select_solicitudes" class="form-control" style="width: 100%;">
                  {% for foo in solicitudes %}
                      <option value="{{ foo.id }}" {% if foo.estado == "terminado" %}disabled{% endif %}>{{ foo.cliente.nombre }} -
                          {{ foo.cliente.rut }} -
                          {{ foo.tema_juridico.nombre_tema }} <>
                          {{ foo.demandado_nombre }} -
                          {{ foo.demandado_rut }}
                      </option>
                  {% endfor %}
                  </select>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                <button onclick="filter()" type="button" class="btn btn-primary">Continuar</button>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
        </div>
{% endblock %}
{% block js %}
<script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>
    <script type="application/javascript">

    $(document).ready(function() {
        $('#select_solicitudes').select2();
    });

    function filter() {

        var select = document.getElementById('select_solicitudes').value;
        window.location.href = ' {% url 'nuevocasojuridico' 0 %}'.replace(/0/, select.toString());
        //alert(select)
    }
    </script>

{% endblock js %}

templates/casojuridico/nuevo.html
{% extends 'base/base.html' %}{% load staticfiles %}
{% block title %} Nuevo usuario {% endblock %}
{% block ccs %}

  <link rel="stylesheet" href="{% static 'bootstrap-daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock ccs %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Por favor, llenar formulario de nuevo caso juridico.</h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <h4>Solicitud</h4>
            </div>
            <div class="col-lg-2">
                <label for="">Cliente:</label>
                <p>{{ solicitud.cliente.nombre }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Rut:</label>
                <p>{{ solicitud.cliente.rut }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Tema Juridico:</label>
                <p title="{{ solicitud.tema_juridico.materia }}">{{ solicitud.tema_juridico.nombre_tema }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Fecha solicitud:</label>
                <p title="">{{ solicitud.fecha_creacion|date:'d - M - Y' }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Demandado:</label>
                <p title="">{{ solicitud.demandado_nombre }}, <b>{{ solicitud.demandado_rut }}</b></p>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <form action="#" method="post">
            {% csrf_token %}
            <div class="row">
                 <div class="col-lg-4 col-xs-12">
                     <label for="id_nombre_caso">Nombre del caso </label>
                    <input type="text" class="form-control" name="nombre_caso" maxlength="40" required id="id_nombre_caso" />
                </div>
                 <div class="col-lg-4 col-xs-12">
                     <label for="id_n_rol_tibunal">Numero Rol Tribunal:</label>
                     <input type="text" class="form-control" autocomplete="off" name="n_rol_tibunal" maxlength="80" required id="id_n_rol_tibunal" />
                 </div>
                 <div class="col-lg-4 col-xs-12">
                     <div class="form-group">
                         <label for="reservation">Fecha inicio y termino:</label>

                         <div class="input-group">
                             <div class="input-group-addon">
                             <i class="fa fa-calendar"></i>
                             </div>
                             <input type="text" name="fechas" class="form-control pull-right" id="reservation">
                         </div>
                        <!-- /.input group -->
                     </div>
                 </div>
                 <div class="col-lg-4 col-xs-12">
                     <label for="id_instancia">Instancia:</label>
                     <input type="text" class="form-control" name="instancia" maxlength="100" required id="id_instancia" />
                 </div>
            </div>

            <div align="right">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <button type="reset" class="btn btn-default">Borrar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'moment/min/moment.min.js' %}"></script>
<script src="{% static 'bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script>
  $(function () {
    $('#reservation').daterangepicker()
  })
</script>
{% endblock js %}