App_Base/urls.py
from django.urls import path
from .views import Home, Login, Logout
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(Home.as_view()),  name='home'),
    path('login/', Login.as_view(),  name='login'),
    path('logout/', login_required(Logout.as_view()),  name='logout')
]

LegalAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Base.urls')),
    path('usuario/', include('App_Usuario.urls')),
    path('calendario/', include('App_Calendario.urls')),
    path('cliente/', include('App_SolicitudCliente.urls')),
    path('casojuridico/', include('App_RegistroCausa.urls'))
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Base/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.

class TipoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class EstadoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class ExtraUser(models.Model):
    user = models.OneToOneField(User, null=False, blank=True, on_delete=models.CASCADE, primary_key=True)
    rut = models.CharField(max_length=10, unique=True)
    tipo = models.ForeignKey(TipoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.user.first_name + ' ' + self.user.last_name)


class GastoOficina(models.Model):
    nombre_gasto = models.CharField(max_length=25)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre_gasto)


class Gastos_User(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    gasto = models.ForeignKey(GastoOficina, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    valor = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.gasto)


class Reunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)
    fecha_inicio = models.CharField(max_length=40, default=False)
    fecha_final = models.CharField(max_length=40, default=False)
    todo_Dia = models.BooleanField(default=False)
    color = models.CharField(max_length=6, default='ffffff')
    tema_reunion = models.CharField(max_length=30)
    observacion = models.TextField(null=False, blank=True)
    caso_juridico = models.IntegerField(default=0)
    url = models.CharField(max_length=200, default=False)

    def __str__(self):
        return '{}'.format(self.tema_reunion + ' ' + str(self.fecha_inicio)+ ' ' + str(self.fecha_final))


class UserReunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    reunion = models.ForeignKey(Reunion, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.reunion)


class Cliente(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.rut + ' ' + self.nombre)


class Materia(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre)


class TemaJuridico(models.Model):
    materia = models.ForeignKey(Materia, blank=True, on_delete=models.CASCADE)
    nombre_tema = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.nombre_tema + ' ' + self.materia.nombre)


class Solicitud(models.Model):
    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=50)
    observaciones = models.TextField()
    demandado_nombre = models.CharField(max_length=100, null=True)
    demandado_rut = models.CharField(max_length=100, null=True)
    demandado_telefono = models.CharField(max_length=100, null=True)
    demandado_direccion = models.CharField(max_length=100, null=True)

    def __str__(self):
        return '{}'.format(self.cliente.nombre + ' ' + self.tema_juridico.nombre_tema)


def generate_path(instance, filename):
    return os.path.join("documents", str(instance.rut), filename)


class DocumentoSolicitud(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.rut)


class Documentacion(models.Model):

    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.rut)


class CasoJuridico(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    nombre_caso = models.CharField(max_length=40)
    fecha_inicio = models.DateField()
    fecha_termino = models.DateField()
    n_rol_tibunal= models.CharField(max_length=80)
    estado = models.CharField(max_length=50)
    instancia = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.nombre_caso)


class UserCaso(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.user.user.username + ' ' + self.caso_juridico.nombre_caso)


class Tribunal(models.Model):
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.nombre)


class Etapa(models.Model):
    caso = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre_etapa = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    descripcion = models.TextField()
    fecha_termini = models.TimeField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_etapa + ' ' + self.caso.nombre_caso)


class Actividad(models.Model):
    etapa = models.ForeignKey(Etapa, blank=True, on_delete=models.CASCADE)
    nombre_actividad = models.CharField(max_length=50)
    fecha_hora = models.DateTimeField()
    descripcion = models.TextField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_actividad)


class Notificacion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    enlace = models.CharField(max_length=100)
    fecha_hora = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.titulo)

App_SolicitudCliente/forms.py
from django import forms


class NuevoClienteForm(forms.Form):

    rut = forms.CharField(max_length=12)
    nombre = forms.CharField(max_length=50)
    tipo = forms.CharField(max_length=50)
    direccion = forms.CharField(max_length=50)
    telefono = forms.IntegerField()
    email = forms.CharField(max_length=50)


class DocumentacionForm(forms.Form):
    #rut = forms.CharField(max_length=10, required=False)
    docfile1 = forms.FileField(required=False)
    docfile2 = forms.FileField(required=False)
    docfile3 = forms.FileField(required=False)
    docfile4 = forms.FileField(required=False)
    docfile5 = forms.FileField(required=False)
    docfile6 = forms.FileField(required=False)
    docfile7 = forms.FileField(required=False)
    docfile8 = forms.FileField(required=False)
    docfile9 = forms.FileField(required=False)
    docfile0 = forms.FileField(required=False)
    
class NuevaSolicitudForm(forms.Form):
    tema_juridico = forms.CharField(max_length=50)
    cliente = forms.CharField(max_length=50)
    observaciones = forms.Textarea()
    demandado_nombre = forms.CharField(max_length=100)
    demandado_rut = forms.CharField(max_length=100)
    demandado_telefono = forms.CharField(max_length=100)
    demandado_direccion = forms.CharField(max_length=100)

templates/client/listadocliente.html
{% extends 'base/base.html' %}{% load staticfiles %}
{% block title %} Nuevo usuario {% endblock %}
{% block ccs %}

  <link rel="stylesheet" href="{% static '/select2/dist/css/select2.min.css' %}">
{% endblock ccs %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <div class="col-lg-6">
            <i class="fa fa-file-text fa-fw"></i>
            <h3 class="box-title"> Listado solicitudes</h3>
        </div>
        <div class="col-lg-6" align="right">
            <a href="">
                <h3 class="box-title"> Crear cliente</h3>
                <i class="fa fa-plus fa-fw"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <div class="list">
            <div class="row header-list" align="center">
                <div class="col-lg-2">
                    Nombre
                </div>
                <div class="col-lg-2">
                    Rut
                </div>
                <div class="col-lg-1">
                    Tipo
                </div>
                <div class="col-lg-2">
                    Direccion
                </div>
                <div class="col-lg-2">
                    Telefono
                </div>
                <div class="col-lg-2">
                    {{ foo.rut }}
                    Email
                </div>
                <div class="col-lg-1">
                    Acciones
                </div>
            </div>
            {% for foo in clientes %}
            <div class="row body-list modal-down" align="center">
                <div class="col-lg-2">
                    {{ foo.nombre }}
                </div>
                <div class="col-lg-2">
                    {{ foo.rut }}
                </div>
                <div class="col-lg-1">
                    {{ foo.tipo }}
                </div>
                <div class="col-lg-2">
                    {{ foo.direccion }}
                </div>
                <div class="col-lg-2">
                    {{ foo.telefono }}
                </div>
                <div class="col-lg-2" title="{{ foo.email }}">
                    {{ foo.email|truncatechars:'20' }}
                </div>
                <div class="col-lg-1">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/client/listadosolicitudes.html
{% extends 'base/base.html' %}
{% block title %} Nuevo usuario {% endblock %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <div class="col-lg-6">
            <i class="fa fa-file-text fa-fw"></i>
            <h3 class="box-title"> Listado solicitudes</h3>
        </div>
        <div class="col-lg-6" align="right">
            <a href="{% url 'nuevasolicitud' %}">
                <h3 class="box-title"> Crear solicitud</h3>
                <i class="fa fa-plus fa-fw"></i>
            </a>
        </div>
    </div>
    <div class="box-body">
        <div class="list">
            <div class="row header-list" align="center">
                <div class="col-lg-2">
                    Cliente
                </div>
                <div class="col-lg-1">
                    Estado
                </div>
                <div class="col-lg-2">
                    Tema Juridico
                </div>
                <div class="col-lg-2">
                    Fecha solicitud
                </div>
                <div class="col-lg-2">
                    Demandado
                </div>
                <div class="col-lg-2">
                    Observaciones
                </div>
            </div>
            {% for foo in solicitudes %}
            <div class="row body-list modal-down" align="center">
                <div class="col-lg-2">
                    <b>{{ foo.cliente.rut }} </b><br>{{ foo.cliente.nombre }}
                </div>
                <div class="col-lg-1">
                    {{ foo.estado }}
                </div>
                <div class="col-lg-2">
                    <b>{{ foo.tema_juridico.nombre_tema }}</b>
                </div>
                <div class="col-lg-2">
                    {{ foo.fecha_creacion|date:'d - F - Y' }}
                </div>
                <div class="col-lg-2">
                    <b>{{ foo.demandado_rut }}</b> <br> {{ foo.demandado_nombre }}
                </div>
                <div class="col-lg-2" title="{{ foo.observaciones }}">
                    {{ foo.observaciones|truncatechars:'20' }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/client/nuevo.html
{% extends 'base/base.html' %}
{% block title %} Nuevo Cliente {% endblock %}
{% block content %}
<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Por favor, complete el siguiente formulario para crear un nuevo cliente.</h3>
    </div>
    <div class="box-body">
        <form action="#" method="post">
            {% csrf_token %}
            <label>Informacion del cliente.</label>
            <div class="row">
                <div class="col-lg-3 col-xs-12">
                    <input name="rut" type="text" class="form-control" autocomplete="off" placeholder="11111111-1" required >
                </div>
                <div class="col-lg-6 col-xs-12">
                     <input name="nombre" type="text" class="form-control" autocomplete="off" placeholder="Nombre" required >
                </div>
                <div class="col-lg-3 col-xs-12">
                    <input name="tipo" type="text"  class="form-control" value="" autocomplete="off"  placeholder="Tipo" required>
                </div>
                <div class="col-lg-4 col-xs-12">
                     <input name="direccion" type="text" class="form-control" value="" autocomplete="off"  placeholder="Direccion" required>
                </div>
                <div class="col-lg-4 col-xs-12">
                    <input name="telefono" type="number" class="form-control" value="" autocomplete="off"  placeholder="Telefono" required>
                </div>
                <div class="col-lg-4 col-xs-12">
                    <input name="email" type="email" class="form-control" value="" autocomplete="off"  placeholder="correo@correo.cl" required>
                </div>
                <div class="col-lg-6 col-xs-12">
                    <p>{{ error }}</p>
                </div>
                <div class="col-lg-6 col-xs-12" align="right">
                    <button type="submit" class="btn btn-primary">Ingresar</button>
                    <button type="reset" class="btn btn-default">Borrar</button>
                </div>
            </div>

            <div align="right">
            </div>
        </form>
    </div>
</div>
<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Listado de usuarios registrados.</h3>
    </div>
    <div class="box-body list">
            <div class="row header-list" align="center">
                <div class="col-lg-2">
                    Rut
                </div>
                <div class="col-lg-2">
                    Nombre
                </div>
                <div class="col-lg-1">
                    Tipo
                </div>
                <div class="col-lg-2">
                    Email
                </div>
                <div class="col-lg-1">
                    Telefono
                </div>
                <div class="col-lg-3">
                    Direccion
                </div>
                <div align="left" class="col-lg-1">
                    Opciones
                </div>
            </div>
            {% for foo in clientes %}
            <div class="row body-list" align="center">
                <div class="col-lg-2">
                    {{ foo.rut }}
                </div>
                <div class="col-lg-2">
                    {{ foo.nombre }}
                </div>
                <div class="col-lg-1">
                    {{ foo.tipo }}
                </div>
                <div class="col-lg-2">
                    {{ foo.email }}
                </div>
                <div class="col-lg-1">
                    {{ foo.telefono }}
                </div>
                <div class="col-lg-3">
                    {{ foo.direccion }}
                </div>
                <div class="col-lg-1">
                    <a href="" title="Editar">
                        <span class="fa fa-edit"></span>
                    </a>
                </div>
            </div>
            {% endfor %}
    </div>
</div>
{% endblock %}

templates/client/solicitud.html
{% extends 'base/base.html' %}
{% block title %} Nuevo usuario {% endblock %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Por favor, complete el siguiente formulario para crear una solicitud.</h3>
    </div>
    <div class="box-body">
        <form action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                 <div class="col-lg-4 col-xs-12">
                <label>Cliente</label>
                    <select name="cliente" class="form-control" id="id_rut">
                        {% if user_ %}
                        <option value="{{ user_.estado.id }}">{{ user_.estado }}</option>
                        {% endif %}
                        {% for foo in clientes %}
                        <option value="{{ foo.id }}">{{ foo }}</option>
                        {% endfor %}
                    </select>
                </div>
                 <div class="col-lg-4 col-xs-12">
                <label>Tema Juridico</label>
                    <select name="tema_juridico" class="form-control">
                        {% if user_ %}
                        <option value="{{ user_.estado.id }}">{{ user_.estado }}</option>
                        {% endif %}
                        {% for foo in tema_juridico %}
                        <option value="{{ foo.id }}">{{ foo }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-xs-12">
                    <h4>Datos Demandado</h4>
                </div>
                <div class="col-lg-4 col-xs-12">
                <label>Nombre</label>
                     <input type="text" class="form-control" name="demandado_nombre" maxlength="100" required />
                </div>
                <div class="col-lg-4 col-xs-12">
                <label>Rut</label>
                     <input type="text" class="form-control" name="demandado_rut" maxlength="100" required />
                </div>
                <div class="col-lg-4 col-xs-12">
                <label>Telefono</label>
                     <input type="text" class="form-control" name="demandado_telefono" maxlength="100" required />
                </div>
                <div class="col-lg-12 col-xs-12">
                <label>Direccion</label>
                     <input type="text" class="form-control" name="demandado_direccion" maxlength="100" required />
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-xs-12">
                    <h4>Observaciones</h4>
                </div>
                 <div class="col-lg-12 col-xs-12">
                     <textarea name="observaciones" class="form-control" style="margin-bottom: 20px"></textarea>
                </div>
            </div>

            <div align="right">
                <button type="submit" class="btn btn-primary">Continuar</button>
                <button type="reset" class="btn btn-default">Borrar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/client/solicitud_doc.html
{% extends 'base/base.html' %}
{% block title %} Nuevo usuario {% endblock %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Por favor, Adjuntar documentos para la solicitud.</h3>
    </div>
    <div class="box-body">
        <form action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile1" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile2" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile3" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile4" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile5" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile6" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile7" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile8" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile9" id="id_docfile1" />
                </div>
                 <div class="col-lg-6 col-xs-12">
                    <input type="file" class="form-control" name="docfile0" id="id_docfile1" />
                </div>
            </div>

            <div align="right">
                <a href="{% url 'listadolicitudes' %}" class="btn btn-primary">Sin Documentos</a>
                <button type="submit" class="btn btn-primary">Guardar</button>
                <button type="reset" class="btn btn-default">Borrar</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}