App_Base/urls.py
from django.urls import path
from .views import Home, Login, Logout
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(Home.as_view()),  name='home'),
    path('login/', Login.as_view(),  name='login'),
    path('logout/', login_required(Logout.as_view()),  name='logout')
]

LegalAssistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Base.urls')),
    path('usuario/', include('App_Usuario.urls')),
    path('calendario/', include('App_Calendario.urls')),
    path('cliente/', include('App_SolicitudCliente.urls')),
    path('casojuridico/', include('App_RegistroCausa.urls'))
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Base/models.py
from django.db import models
from django.contrib.auth.models import User
import os

# Create your models here.

class TipoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class EstadoUser(models.Model):
    titulo = models.CharField(max_length=20, unique=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.titulo)


class ExtraUser(models.Model):
    user = models.OneToOneField(User, null=False, blank=True, on_delete=models.CASCADE, primary_key=True)
    rut = models.CharField(max_length=10, unique=True)
    tipo = models.ForeignKey(TipoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    estado = models.ForeignKey(EstadoUser, null=False, blank=True, default=1, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.user.first_name + ' ' + self.user.last_name)


class GastoOficina(models.Model):
    nombre_gasto = models.CharField(max_length=25)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.nombre_gasto)


class Gastos_User(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    gasto = models.ForeignKey(GastoOficina, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    valor = models.IntegerField(null=True, blank=True)
    descripcion = models.TextField(null=False, blank=True)

    def __str__(self):
        return '{}'.format(self.gasto)


class Reunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)
    fecha_inicio = models.CharField(max_length=40, default=False)
    fecha_final = models.CharField(max_length=40, default=False)
    todo_Dia = models.BooleanField(default=False)
    color = models.CharField(max_length=6, default='ffffff')
    tema_reunion = models.CharField(max_length=30)
    observacion = models.TextField(null=False, blank=True)
    caso_juridico = models.IntegerField(default=0)
    url = models.CharField(max_length=200, default=False)

    def __str__(self):
        return '{}'.format(self.tema_reunion + ' ' + str(self.fecha_inicio)+ ' ' + str(self.fecha_final))


class UserReunion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    reunion = models.ForeignKey(Reunion, blank=True, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.reunion)


class Cliente(models.Model):
    rut = models.CharField(max_length=12)
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField()
    email = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.rut + ' ' + self.nombre)


class Materia(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()

    def __str__(self):
        return '{}'.format(self.nombre)


class TemaJuridico(models.Model):
    materia = models.ForeignKey(Materia, blank=True, on_delete=models.CASCADE)
    nombre_tema = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.nombre_tema + ' ' + self.materia.nombre)


class Solicitud(models.Model):
    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, blank=True, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=50)
    observaciones = models.TextField()
    demandado_nombre = models.CharField(max_length=100, null=True)
    demandado_rut = models.CharField(max_length=100, null=True)
    demandado_telefono = models.CharField(max_length=100, null=True)
    demandado_direccion = models.CharField(max_length=100, null=True)

    def __str__(self):
        return '{}'.format(self.cliente.nombre + ' ' + self.tema_juridico.nombre_tema)


def generate_path(instance, filename):
    return os.path.join("documents", str(instance.rut), filename)


class DocumentoSolicitud(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.rut)


class Documentacion(models.Model):

    tema_juridico = models.ForeignKey(TemaJuridico, blank=True, on_delete=models.CASCADE)
    #nombre = models.CharField(max_length=50)
    rut = models.CharField(max_length=10)
    docfile = models.FileField(upload_to=generate_path, null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.rut)


class CasoJuridico(models.Model):
    solicitud = models.ForeignKey(Solicitud, blank=True, on_delete=models.CASCADE)
    nombre_caso = models.CharField(max_length=40)
    fecha_inicio = models.DateField()
    fecha_termino = models.DateField()
    n_rol_tibunal= models.CharField(max_length=80)
    estado = models.CharField(max_length=50)
    instancia = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.solicitud.cliente.nombre + ' ' + self.nombre_caso)


class UserCaso(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.user.user.username + ' ' + self.caso_juridico.nombre_caso)


class Tribunal(models.Model):
    caso_juridico = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.nombre)


class Etapa(models.Model):
    caso = models.ForeignKey(CasoJuridico, blank=True, on_delete=models.CASCADE)
    nombre_etapa = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    descripcion = models.TextField()
    fecha_termini = models.TimeField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_etapa + ' ' + self.caso.nombre_caso)


class Actividad(models.Model):
    etapa = models.ForeignKey(Etapa, blank=True, on_delete=models.CASCADE)
    nombre_actividad = models.CharField(max_length=50)
    fecha_hora = models.DateTimeField()
    descripcion = models.TextField()
    estado = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.nombre_actividad)


class Notificacion(models.Model):
    user = models.ForeignKey(ExtraUser, blank=True, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    descripcion = models.TextField()
    enlace = models.CharField(max_length=100)
    fecha_hora = models.DateTimeField()

    def __str__(self):
        return '{}'.format(self.titulo)

templates/calendario/agendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/calendario/calendario.html
{% extends 'base/base.html' %}{% load staticfiles %}
{% block ccs %}
  <!-- fullCalendar -->
  <link rel="stylesheet" href="{% static 'fullcalendar/dist/fullcalendar.min.css' %}">
  <link rel="stylesheet" href="{% static 'fullcalendar/dist/fullcalendar.print.min.css' %}" media="print">


  <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock ccs %}
{% block content %}
      <div class="row">
        <!-- /.col -->
          <div class="col-md-12">
          <div class="box box-primary">
            <div class="box-body no-padding">
              <div class="row">
                  <div class="col-md-8 col-xs-12">
                    <div id="calendar"></div>
                  </div>
                  <div class="col-md-4 col-xs-12" style="">
                    <div class="col-lg-12 col-xs-12" align="center">
                        <h4>Agregar reunion</h4>
                    </div>
                        <form action="" method="post">
                  {% csrf_token %}
                    <div class="col-lg-12 col-xs-12">
                        <div class="form-group">
                        <label>Fecha y hora de reunion:</label>

                        <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                          </div>
                          <input name="fechas" type="text" class="form-control pull-right" id="fechas">
                        </div>
                        <!-- /.input group -->
                      </div>
                    </div>
                    <div class="col-lg-12 col-xs-12">
                        <label for="id_tema_reunion">Tema reunion:</label>
                        <input class="form-control" type="text" onkeyup="add_color(false)" name="tema_reunion" maxlength="30" required id="id_tema_reunion" />
                    </div>
                    <div class="col-lg-12 col-xs-12">
                        <label for="id_color">Color:</label>
                        <ul class="fc-color-picker" id="color-chooser">
                          <li><a class="text-aqua" href="" onclick="add_color('00c0ef')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-blue" href="#" onclick="add_color('0073b7')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-light-blue" href="#" onclick="add_color('3c8dbc')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-teal" href="#" onclick="add_color('39cccc')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-yellow" href="#" onclick="add_color('f39c12')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-red" href="#" onclick="add_color('dd4b39')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-purple" href="#" onclick="add_color('605ca8')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-fuchsia" href="#" onclick="add_color('f012be')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-muted" href="#" onclick="add_color('777777')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-navy" href="#" onclick="add_color('001f3f')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-black" href="#" onclick="add_color('111111')"><i class="fa fa-square"></i></a></li>
                        </ul>
                    </div>
                    <input hidden name="color" id="id_color">

                    <div class="col-lg-12 col-xs-12">
                        <label for="id_observacion">Observacion:</label>
                        <textarea name="observacion" id="id_observacion" class="form-control" rows="6"></textarea>
                    </div>
                    <div class="col-lg-12 col-xs-12">
                        <label for="id_caso_juridico">Asignar caso juridico:</label>
                        <select name="caso_juridico" id="id_caso_juridico" class="form-control">
                            <option value="0">Sin Caso</option>
                            {% for foo in casos %}
                            <option value="{{ foo.id }}">{{ foo.solicitud.cliente.nombre }} <b>{{ foo.solicitud.cliente.rut }}</b> -{{ foo.nombre_caso }} - {{ foo.n_rol_tibunal }}</option>
                            {% endfor %}

                        </select>
                    </div>
                    <div class="col-lg-6 col-xs-12">
                        <label for="">Vista Previa</label>
                        <div id="demo" class="demo_calendario">
                            Vista Previa
                        </div>
                    </div>
                    <div class="col-lg-6 col-xs-12" align="center">
                        <input class="btn btn-default" type="submit" value="Agregar" style="margin-top: 40px">
                    </div>
              </form>
                  </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
{% endblock content %}
{%  block js %}
<script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'moment/moment.js' %}"></script>
<script src="{% static 'fullcalendar/dist/fullcalendar.min.js' %}"></script>
<script>
  $(function () {

    /* initialize the external events
     -----------------------------------------------------------------*/
    function init_events(ele) {
      ele.each(function () {

        // create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
        // it doesn't need to have a start or end
        var eventObject = {
          title: $.trim($(this).text()) // use the element's text as the event title
        }

        // store the Event Object in the DOM element so we can get to it later
        $(this).data('eventObject', eventObject)

        // make the event draggable using jQuery UI
        $(this).draggable({
          zIndex        : 1070,
          revert        : true, // will cause the event to go back to its
          revertDuration: 0  //  original position after the drag
        })

      })
    }

    init_events($('#external-events div.external-event'))

    /* initialize the calendar
     -----------------------------------------------------------------*/
    //Date for the calendar events (dummy data)


      {% for foo in calendario %}

        console.log('{{ ll.fecha_inicio }}')
      {% endfor %}
    $('#calendar').fullCalendar({
      header    : {
        left  : 'prev,next today',
        center: 'title',
        right : 'month,agendaWeek,agendaDay'
      },
      buttonText: {
        today: 'Hoy',
        month: 'Mes',
        week : 'Semana',
        day  : 'Dia'
      },
      //Random default events

      events    : [
          {% for ll in calendario %}
        {
          title          : '{{ ll.tema_reunion }}',
          start          : new Date(
              '{{ ll.fecha_inicio.ano }}',
              '{{ ll.fecha_inicio.mes }}',
              '{{ ll.fecha_inicio.dia }}',
              '{{ ll.fecha_inicio.hora }}',
              '{{ ll.fecha_inicio.minuto }}'
          ),
          end            : new Date(
              '{{ ll.fecha_final.ano }}',
              '{{ ll.fecha_final.mes }}',
              '{{ ll.fecha_final.dia }}',
              '{{ ll.fecha_final.hora }}',
              '{{ ll.fecha_final.minuto }}'
          ),
          url            : '{% url 'detallereunion' ll.id %}',
          backgroundColor: '#{{ ll.color }}', //yellow
          borderColor    : '#{{ ll.color }}' //yellow
        },
          {% endfor %}
         /*,
        {
          title          : 'Meeting',
          start          : new Date(y, m, d, 10, 30),
          allDay         : false,
          backgroundColor: '#0073b7', //Blue
          borderColor    : '#0073b7' //Blue
        },
        {
          title          : 'Lunch',
          start          : new Date(y, m, d, 12, 0),
          end            : new Date(y, m, d, 14, 0),
          allDay         : false,
          backgroundColor: '#00c0ef', //Info (aqua)
          borderColor    : '#00c0ef' //Info (aqua)
        },
        {
          title          : 'Birthday Party',
          start          : new Date(y, m, d + 1, 19, 0),
          end            : new Date(y, m, d + 1, 22, 30),
          allDay         : true,
          backgroundColor: '#00a65a', //Success (green)
          borderColor    : '#00a65a' //Success (green)
        },
        {
          title          : 'Click for Google',
          start          : new Date(y, m, 30),
          end            : new Date(y, 2, 29),
          url            : 'http://google.com/',
          backgroundColor: '#3c8dbc', //Primary (light-blue)
          borderColor    : '#3c8dbc' //Primary (light-blue)
        }*/
      ],
      editable  : true,
      droppable : true, // this allows things to be dropped onto the calendar !!!
      drop      : function (date, allDay) { // this function is called when something is dropped

        // retrieve the dropped element's stored Event Object
        var originalEventObject = $(this).data('eventObject')

        // we need to copy it, so that multiple events don't have a reference to the same object
        var copiedEventObject = $.extend({}, originalEventObject)

        // assign it the date that was reported
        copiedEventObject.start           = date
        copiedEventObject.allDay          = allDay
        copiedEventObject.backgroundColor = $(this).css('background-color')
        copiedEventObject.borderColor     = $(this).css('border-color')

        // render the event on the calendar
        // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
        $('#calendar').fullCalendar('renderEvent', copiedEventObject, true)

        // is the "remove after drop" checkbox checked?
        if ($('#drop-remove').is(':checked')) {
          // if so, remove the element from the "Draggable Events" list
          $(this).remove()
        }

      }
    })

    /* ADDING EVENTS */
    var currColor = '#3c8dbc' //Red by default
    //Color chooser button
    var colorChooser = $('#color-chooser-btn')
    $('#color-chooser > li > a').click(function (e) {
      e.preventDefault()
      //Save color
      currColor = $(this).css('color')
      //Add color effect to button
      $('#add-new-event').css({ 'background-color': currColor, 'border-color': currColor })
    })
    $('#add-new-event').click(function (e) {
      e.preventDefault()
      //Get value and make sure it is not null
      var val = $('#new-event').val()
      if (val.length == 0) {
        return
      }

      //Create events
      var event = $('<div />')
      event.css({
        'background-color': currColor,
        'border-color'    : currColor,
        'color'           : '#fff'
      }).addClass('external-event')
      event.html(val)
      $('#external-events').prepend(event)

      //Add draggable funtionality
      init_events(event)

      //Remove event from text input
      $('#new-event').val('')
    })
  })
</script>
<script src="{% static 'moment/min/moment.min.js' %}"></script>
<script src="{% static 'bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<script>
$(function() {
    $('input[name="fechas"]').daterangepicker({
        timePicker: true,
        timePickerIncrement: 5,

        "timePicker24Hour": true,
        locale: {
            format: 'MM/DD/YYYY h:mm A'
        }
    });
});
function add_color(color) {
    if (color) {
        document.getElementById("id_color").value = color;
        obj = document.getElementById('demo');
        obj.style.backgroundColor = '#' + color;
        console.log(document.getElementById("id_tema_reunion").value);
        if (!document.getElementById("id_tema_reunion").value){
            document.getElementById('demo').innerHTML = "Vista Previa"
        }
    }
    document.getElementById('demo').innerHTML = document.getElementById("id_tema_reunion").value;
}
</script>
<script src="{% static 'select2/dist/js/select2.full.min.js' %}"></script>
    <script type="application/javascript">
    $(document).ready(function() {
        $('#id_caso_juridico').select2();
    });
</script>
{% endblock js %}

templates/calendario/detallereunion.html
{% extends 'base/base.html' %}{% load staticfiles %}
{% block title %} Detalle Reunion {% endblock %}
{% block ccs %}
  <link rel="stylesheet" href="{% static 'select2/dist/css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-daterangepicker/daterangepicker.css' %}">
  <link rel="stylesheet" href="{% static 'bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock ccs %}
{% block content %}

<div class="box box-default">
    <div class="box-header with-border">
        <i class="fa fa-user-plus fa-fw"></i>
        <h3 class="box-title"> Detalle reunion</h3>
    </div>
    <div class="box-body" id="muestra">
        <div class="row">
            <div class="col-lg-2">
                <label for="">Tema Reunion:</label>
                <p>{{ reunion.tema_reunion }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Fecha inicio:</label>
                <p>{{ reunion.fecha_inicio }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Fecha termino:</label>
                <p>{{ reunion.fecha_final }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Color:</label>
                <div class="demo_calendario" style="background-color: #{{ reunion.color }}">
                    {{ reunion.tema_reunion }}
                </div>
            </div>
        </div>
    {% if caso %}

        <div class="row">
            <div class="col-lg-12">
                <h3>Caso Juridico</h3>
            </div>
            <div class="col-lg-2">
                <label for="">Cliente:</label>
                <p>{{ caso.solicitud.cliente.nombre }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Demandado:</label>
                <p>{{ caso.solicitud.demandado_nombre }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Estado Solicitud:</label>
                <p>{{ caso.solicitud.estado }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Tema Juridico:</label>
                <p>{{ caso.solicitud.tema_juridico.nombre_tema }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Nombre del caso:</label>
                <p>{{ caso.nombre_caso }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">N° rol tribunal:</label>
                <p>{{ caso.n_rol_tibunal }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Estado del caso:</label>
                <p>{{ caso.estado }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Fecha Inicio:</label>
                <p>{{ caso.fecha_inicio }}</p>
            </div>
            <div class="col-lg-2">
                <label for="">Fecha termino:</label>
                <p>{{ caso.fecha_termino }}</p>
            </div>
        </div>
    {% endif %}
        <div class="row">
            <div class="col-lg-12">
                <h3>Observaciones</h3>
            </div>
            <div class="col-lg-12">
                <p>{{ reunion.observacion }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12" align="right">
                <button onclick="cambiar_a()" class="btn btn-default">Editar</button>
            </div>
        </div>
    </div>
    <div class="box-body" id="edita" style="display: none">
        <form action="" method="post">
        {% csrf_token %}
            <div class="row">
                <div class="col-lg-4">
                    <label for="id_tema_reunion">Tema Reunion:</label>
                    <input class="form-control"  value="{{ reunion.tema_reunion }}" type="text" onkeyup="add_color(false)" name="tema_reunion" maxlength="30" required id="id_tema_reunion" />
                </div>
                <div class="col-lg-4">
                        <div class="form-group">
                        <label>Fecha y hora de reunion:</label>

                        <div class="input-group">
                          <div class="input-group-addon">
                            <i class="fa fa-clock-o"></i>
                          </div>
                          <input name="fechas" type="text" class="form-control pull-right" id="fechas">
                        </div>
                        <!-- /.input group -->
                      </div>
                </div>
                <div class="col-lg-4">
                    <label for="">Color:</label>
                        <div id="demo" class="demo_calendario" style="background-color:#{{ reunion.color }} ;max-width: 200px;">
                            {{ reunion.tema_reunion }}
                        </div>
                        <ul class="fc-color-picker" id="color-chooser">
                          <li><a class="text-aqua" href="" onclick="add_color('00c0ef')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-blue" href="#" onclick="add_color('0073b7')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-light-blue" href="#" onclick="add_color('3c8dbc')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-teal" href="#" onclick="add_color('39cccc')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-yellow" href="#" onclick="add_color('f39c12')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-red" href="#" onclick="add_color('dd4b39')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-purple" href="#" onclick="add_color('605ca8')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-fuchsia" href="#" onclick="add_color('f012be')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-muted" href="#" onclick="add_color('777777')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-navy" href="#" onclick="add_color('001f3f')"><i class="fa fa-square"></i></a></li>
                          <li><a class="text-black" href="#" onclick="add_color('111111')"><i class="fa fa-square"></i></a></li>
                        </ul>
                        <input hidden name="color" id="id_color">
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-xs-12">
                    <label for="id_caso_juridico">Asignar caso juridico:</label>
                    <select name="caso_juridico" id="id_caso_juridico" class="form-control">
                        <option value="{{ caso.id }}">{{ caso }}</option>
                        {% for foo in casos %}
                        <option value="{{ foo.id }}">{{ foo.solicitud.cliente.nombre }} <b>{{ foo.solicitud.cliente.rut }}</b> -{{ foo.nombre_caso }} - {{ foo.n_rol_tibunal }}</option>
                        {% endfor %}

                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h3>Observaciones</h3>
                </div>
                <div class="col-lg-12">
                    <textarea name="observacion" id="id_observacion" class="form-control" rows="6">{{ reunion.observacion }}</textarea>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12" align="right" style="margin-top: 20px">
                    <button onclick="cambiar_b()" type="button" class="btn btn-default">Atras</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>

                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}
{% block js %}

<script src="{% static 'moment/min/moment.min.js' %}"></script>
<script src="{% static 'bootstrap-daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<script>
$(function() {
    $('input[name="fechas"]').daterangepicker({
        timePicker: true,
        timePickerIncrement: 5,

        "startDate": "{{ reunion.fecha_inicio }}",
        "endDate": "{{ reunion.fecha_final }}",
        "timePicker24Hour": true,
        locale: {
            format: 'MM/DD/YYYY h:mm A'
        }
    });
});
function add_color(color) {
    if (color) {
        document.getElementById("id_color").value = color;
        obj = document.getElementById('demo');
        obj.style.backgroundColor = '#' + color;
        console.log(document.getElementById("id_tema_reunion").value);
        if (!document.getElementById("id_tema_reunion").value){
            document.getElementById('demo').innerHTML = "Vista Previa"
        }
    }
    document.getElementById('demo').innerHTML = document.getElementById("id_tema_reunion").value;
}
function cambiar_a() {
    document.getElementById('muestra').style.display = 'none';
    document.getElementById('edita').style.display = '';
}
function cambiar_b() {
    document.getElementById('muestra').style.display = '';
    document.getElementById('edita').style.display = 'none';
}
</script>
{% endblock js %}